### ISSUE TITLE
Dockerfile: bust cache when installing binary image from fixed URL

### ISSUE THREAD

**Issue by gllmflndn** [mtmiller/octave-snapshot#2]
* I think the `octave-ubuntu-trusty-snapshot.tar.xz` archive is going to be cached even if its content changes because the checksum is on the `RUN` statement. Maybe use `ADD` again?
* Are all the installed packages necessary? Especially the ones relating to compilation or the `-dev` ones.
* I was looking at enabling X11. I tried:
```
xhost local:root
docker run -ti -e DISPLAY=$DISPLAY -v /tmp:/tmp -v /tmp/.X11-unix:/tmp/.X11-unix mtmiller/octave-snapshot
```
The "Welcome to GNU Octave" window opens successfully but it's followed by a segfault when closing that window.
If I start `octave-cli`, a figure can be opened with fltk (selected by default) and Qt is not available.

**Comment by mtmiller** [comment]
> I think the octave-ubuntu-trusty-snapshot.tar.xz archive is going to be cached even if its content changes because the checksum is on the RUN statement. Maybe use ADD again?

I don't think so, because with two steps it would first add the tarball to the root filesystem, cache that, then extract it and cache the result. This way it is downloading the file and extracting it directly, it never touches the filesystem. The best practices docs recommend to always use `curl -SL URL | tar -x`. But if you can demonstrate that another way is better I will do it.

> Are all the installed packages necessary? Especially the ones relating to compilation or the -dev ones.

Yes, because the primary purpose of this container is to test the user's own code or packages against Octave, and `mkoctfile` requires the compilers and development libraries that I added to the list. I worked this list up incrementally myself, as far as I can tell they are all necessary to build a standard oct file. `gdb` is the only one that's not strictly necessary.

> I was looking at enabling X11.

Good, I'd be happy to add instructions on how to do that or make whatever minimal changes I can to enable that, I have not looked into it yet.

**Comment by mtmiller** [comment]
The difference in layer size between the final image and its parent is 594 MB, which is exactly the size of the uncompressed contents of the Octave binary downloaded and extracted. This seems to confirm that the additional 101 MB of the compressed archive itself is not cached anywhere.

**Comment by mtmiller** [comment]
See #4 and #5 for some specifics aimed at reducing the docker image size as much as possible.

**Comment by gllmflndn** [comment]
Thanks for the feedback and opening specific issues.

Regarding the `octave-ubuntu-trusty-snapshot.tar.xz` archive, what I mean is that if you build the container from the Dockerfile then update the archive on AWS and build again, the new version of the archive will not be used and the cached layer will be used instead as the checksum is on the `RUN` line (unchanged) and not on the archive file (changed). I might be wrong but that's my understanding of how things work - maybe it's not an issue in the way you build the container.

**Comment by mtmiller** [comment]
Ok, I see a few topics about this, you are right. This is not a big problem with the current deployment using Docker Hub's automated builds, because they build with the `--no-cache` option. However, anyone trying to replicate this may run into such a problem.

A good suggestion I've seen is to `ADD` a much smaller file, such as a checksum or manifest file, whose mtime will be updated along with the larger file. This should bust the cache at that point and allow the following command to run unconditionally.
